/**
 * Copyright 2026 Gilang Albathin Nurhabibi <https://github.com/athron98>
 *
 * Author: Gilang Albathin Nurhabibi <https://github.com/athron98>
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License. See the LICENSE file at the repository root.
 *
 * `hamolus add plugin <name>` — add a console plugin to an existing console.
 *
 * Plugins are opt-in by design. A console generated by `hamolus add console` lists
 * no plugins, shows no plugin routes, and has no plugin navigation: the CLI is what
 * puts a plugin in, so the base console stays small and the dependency stays visible
 * in the project's own manifest.
 *
 * Registration happens in `console.config.ts` and nowhere else. The console is
 * distributed as a Vite bundle, so a `src/plugins/registry.ts` inside it is a file the
 * project does not own: hand-editing it does nothing, and regenerating the console
 * overwrites it. The config is the one file a host is meant to edit, and it already
 * exists for host-level choices, so the plugin list lives there too. That makes
 * "add a plugin" a one-file change — which is the whole point of the command.
 *
 * There is deliberately no plugin folder either. The command declares the plugin
 * package in the console manifest and adds one import plus one array element; it never
 * copies plugin source into the project. Vendoring the source would move the cost to
 * the host instead of removing it: copied `.tsx` and `*.stylex.ts` files only build if
 * the host adds `vite-plugin-solid` and a StyleX compiler, so "add a plugin" would
 * quietly turn into "add a plugin and reconfigure your build". Plugin packages ship
 * compiled — JavaScript plus their own stylesheet — which is what keeps a host's
 * `vite.config.ts` empty. `--source` / `--package` are therefore retired here for the
 * same reason they are on `hamolus add console`; `hamolus link <path>` still points a
 * project at a local checkout of the packages.
 */

import { existsSync, readFileSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join, relative } from 'node:path'
import type { ParsedArgs } from '../args.js'
import { fallbackRange, resolveWorkspaceDependencyVersion } from '../sources.js'
import { formatLabel } from '../templates.js'
import {
  assertTemplateNotSource,
  commit,
  info,
  openContext,
  requirePartName,
  warn,
  type AddContext,
} from './shared.js'

/** Known plugin packages, so `hamolus add plugin todo` can find a sensible source. */
const KNOWN_PLUGINS: Record<string, { package: string; label: string }> = {
  todo: {
    package: '@hamolus/plugin-console-todo',
    label: 'Todo list',
  },
  kanban: {
    package: '@hamolus/plugin-console-kanban',
    label: 'Kanban board',
  },
}

function pluginPackageName(name: string): string {
  return KNOWN_PLUGINS[name]?.package ?? `@hamolus/plugin-console-${name.replace(/_/g, '-')}`
}

function pluginLabel(name: string): string {
  return KNOWN_PLUGINS[name]?.label ?? formatLabel(name)
}

const IMPORTS_MARKER_START = '/* hamolus:plugins:imports:start */'
const IMPORTS_MARKER_END = '/* hamolus:plugins:imports:end */'
const ENTRIES_MARKER_START = '/* hamolus:plugins:start */'
const ENTRIES_MARKER_END = '/* hamolus:plugins:end */'

/** Where the host-level console config lives, relative to the console root. */
const CONSOLE_CONFIG = 'console.config.ts'

/**
 * Export name a plugin package is expected to publish its descriptor under.
 *
 * `todo` becomes `todoPlugin`. Deriving the name beats storing it: the package that
 * owns the plugin also owns the export, so the CLI never keeps a second list of
 * plugin exports in sync with the packages themselves.
 */
function pluginDescriptorName(name: string): string {
  const [first = '', ...rest] = name.split(/[_-]/).filter(Boolean)
  const camel = [first.toLowerCase(), ...rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1))]
  return `${camel.join('')}Plugin`
}

interface RegistryEntry {
  id: string
  /** Export name imported from the plugin package. */
  descriptor: string
  /** Import specifier written into the config's import marker. */
  specifier: string
}

/** Return the text between a marker pair, or `undefined` if the pair is absent. */
function blockBetween(
  current: string,
  startMarker: string,
  endMarker: string,
): string | undefined {
  const start = current.indexOf(startMarker)
  const end = current.indexOf(endMarker)
  if (start === -1 || end === -1 || end <= start) return undefined
  return current.slice(start + startMarker.length, end)
}

/** Replace the text between a marker pair, returning `undefined` if absent. */
function replaceBetween(
  current: string,
  startMarker: string,
  endMarker: string,
  replacement: string,
  closingIndent = '',
): string | undefined {
  const start = current.indexOf(startMarker)
  const end = current.indexOf(endMarker)
  if (start === -1 || end === -1 || end <= start) return undefined
  const head = current.slice(0, start + startMarker.length)
  const tail = current.slice(end)
  const body = replacement ? `\n${replacement}\n${closingIndent}` : `\n${closingIndent}`
  return `${head}${body}${tail}`
}

/**
 * Leading whitespace of the line a marker sits on.
 *
 * The markers are indented to match the array they live in, and an inserted line has to
 * match too — otherwise a second run re-reads its own output and the block slowly walks
 * out of the array. Deriving the indent from the file beats hard-coding it: the same
 * command has to produce aligned output in the template and in a config a host has
 * reformatted.
 */
function indentOf(current: string, marker: string): string {
  const at = current.indexOf(marker)
  if (at === -1) return ''
  const lineStart = current.lastIndexOf('\n', at) + 1
  const before = current.slice(lineStart, at)
  return /^\s*$/.test(before) ? before : ''
}

/** Render the `import` statements for the imports marker pair, one per line. */
function renderImports(entries: RegistryEntry[], indent: string): string {
  return entries
    .map((entry) => `${indent}import { ${entry.descriptor} } from '${entry.specifier}'`)
    .join('\n')
}

/** Render the array elements for the entries marker pair, one per line. */
function renderEntries(entries: RegistryEntry[], indent: string): string {
  return entries.map((entry) => `${indent}${entry.descriptor},`).join('\n')
}

/**
 * Best-effort plugin id for an already-registered entry, from its specifier.
 *
 * Handles both a bare package specifier (`@hamolus/plugin-console-todo`) and the
 * relative form written by older revisions of this command
 * (`./src/plugins/todo/src/index`). The `/src/index` suffix has to come off *before*
 * the last segment is taken — taking it first yields the literal `index` for every
 * relative specifier, which would make every entry look like a different plugin and let
 * a re-run append a duplicate.
 */
function idFromSpecifier(specifier: string): string {
  const withoutEntry = specifier.replace(/\/src\/index(\.[jt]sx?)?$/, '')
  const tail = withoutEntry.split('/').pop() ?? ''
  return tail
    .replace(/^plugin-console-/, '')
    .replace(/\.(m|c)?[jt]sx?$/, '')
}

/**
 * Whether an already-installed plugin package publishes `descriptor`.
 *
 * Best effort by design: the import is written before anything is installed, so a
 * package that is not in `node_modules` yet cannot be inspected and the check is
 * skipped. When it *is* installed, a package that only exports its page component
 * would otherwise surface as a build error pointing at a file this command had just
 * written; catching it here names the fix in the same run.
 */
function descriptorIsPublished(consoleRoot: string, packageName: string, descriptor: string): boolean {
  let manifestPath: string
  try {
    manifestPath = createRequire(join(consoleRoot, 'package.json')).resolve(`${packageName}/package.json`)
  } catch {
    return true
  }
  const types = join(dirname(manifestPath), 'dist', 'index.d.ts')
  if (!existsSync(types)) return true
  return new RegExp(
    `export\\s+(?:declare\\s+)?(?:const|let|var)\\s+${descriptor}\\b|export\\s*\\{[^}]*\\b${descriptor}\\b`,
  ).test(readFileSync(types, 'utf8'))
}

/**
 * Add a plugin to the console's `console.config.ts`.
 *
 * The two marker blocks are parsed into entries and re-rendered in full rather than
 * patched line by line. That makes the operation idempotent — running it twice is a
 * no-op — order-stable, and safe to re-run after the file has been reformatted, which
 * is what a marker contract actually has to survive.
 *
 * Returns `true` when the file changed.
 */
async function registerPlugin(
  consoleRoot: string,
  name: string,
  specifier: string,
): Promise<boolean> {
  const configPath = join(consoleRoot, CONSOLE_CONFIG)
  if (!existsSync(configPath)) {
    throw new Error(
      `${CONSOLE_CONFIG} is missing from ${consoleRoot}. It is where the plugin list ` +
        'lives — restore it, or re-add the console with `hamolus add console`.',
    )
  }

  const descriptor = pluginDescriptorName(name)
  if (!descriptorIsPublished(consoleRoot, specifier, descriptor)) {
    throw new Error(
      `${specifier} does not export \`${descriptor}\`.\n` +
        'A console plugin package must export its finished descriptor — id, name, ' +
        'description, and page component together — because that descriptor is all ' +
        `\`${CONSOLE_CONFIG}\` needs. Add it as:\n\n` +
        `  export const ${descriptor}: ConsolePlugin = {\n` +
        `    id: '${name}',\n` +
        '    name, description,\n' +
        '    component: YourPage,\n' +
        '  }\n',
    )
  }

  const current = await readFile(configPath, 'utf8')

  const importBlock = blockBetween(current, IMPORTS_MARKER_START, IMPORTS_MARKER_END) ?? ''
  const imports = new Map<string, string>()
  for (const match of importBlock.matchAll(/import\s*\{\s*(\w+)\s*\}\s*from\s*'([^']+)'/g)) {
    const [, identifier, importedFrom] = match
    if (!identifier || !importedFrom) continue
    imports.set(identifier, importedFrom)
  }

  const entryBlock = blockBetween(current, ENTRIES_MARKER_START, ENTRIES_MARKER_END) ?? ''
  const entries: RegistryEntry[] = []
  for (const match of entryBlock.matchAll(/^\s*(\w+),?\s*$/gm)) {
    const identifier = match[1]
    if (!identifier) continue
    const specifierForEntry = imports.get(identifier)
    if (!specifierForEntry) continue
    entries.push({
      id: idFromSpecifier(specifierForEntry),
      descriptor: identifier,
      specifier: specifierForEntry,
    })
  }

  if (entries.some((entry) => entry.id === name)) return false

  entries.push({ id: name, descriptor, specifier })

  const entryIndent = indentOf(current, ENTRIES_MARKER_END)
  const withEntries = replaceBetween(
    current,
    ENTRIES_MARKER_START,
    ENTRIES_MARKER_END,
    renderEntries(entries, entryIndent),
    entryIndent,
  )
  if (!withEntries) {
    throw new Error(
      `${CONSOLE_CONFIG} has no plugin markers. The command appends to the ` +
        '`plugins` array marked with `/* hamolus:plugins:start */` — restore the ' +
        'markers, or add the import and the array element by hand.',
    )
  }
  const importIndent = indentOf(current, IMPORTS_MARKER_END)
  const next = replaceBetween(
    withEntries,
    IMPORTS_MARKER_START,
    IMPORTS_MARKER_END,
    renderImports(entries, importIndent),
    importIndent,
  )
  if (!next || next === current) return false

  await writeFile(configPath, next, 'utf8')
  return true
}

/**
 * Declare the plugin package in the console manifest.
 *
 * The plugin is a real dependency of the console: `console.config.ts` imports it by
 * name, and the host's build reads its compiled JavaScript and its stylesheet from
 * there. Nothing is copied into the project, so this line is the whole installation.
 *
 * The range is taken from a linked checkout when there is one, because a `workspace:`
 * range would be meaningless outside this monorepo; `commit` then rewrites `@hamolus/*`
 * entries to `link:` so a linked project installs before anything is published.
 *
 * Without a linked checkout there is no version to read, and `*` is the wrong answer
 * twice over: it silently accepts any future major of an unreleased package, and it
 * disagrees with the range the console template and {@link resolveDependencyRange}
 * already write. The same fallback is used there, for the same reason — the generated
 * project stays installable against a package that is not on the registry yet.
 */
async function ensurePluginDependency(
  context: AddContext,
  consoleRoot: string,
  packageName: string,
): Promise<string | undefined> {
  const manifestPath = join(consoleRoot, 'package.json')
  let manifest: {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }
  try {
    manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  } catch {
    return undefined
  }

  const existing =
    manifest.dependencies?.[packageName] ?? manifest.devDependencies?.[packageName]
  if (existing) return undefined

  // Per package, not one constant: the plugins version independently of the core
  // packages, so a shared fallback would hand this one a range it was never
  // published at, and `pnpm install` would fail on a name the user never typed.
  const discovered = await resolveWorkspaceDependencyVersion(context.projectRoot, packageName)
  const range = discovered ? `^${discovered.replace(/^[\^~]/, '')}` : fallbackRange(packageName)

  manifest.dependencies ??= {}
  manifest.dependencies[packageName] = range
  // Keep the object stable for reproducible diffs instead of appending blindly.
  manifest.dependencies = Object.fromEntries(
    Object.entries(manifest.dependencies).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  )
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)
  return range
}

export async function runAddPlugin(args: ParsedArgs): Promise<void> {
  const context = await openContext(args)
  const name = requirePartName(args, 'plugin')

  assertTemplateNotSource(args, 'plugin')

  const consoleRoot = join(context.projectRoot, 'console')
  if (!existsSync(join(consoleRoot, 'package.json'))) {
    throw new Error(
      'This project has no console yet. Add one first:\n  hamolus add console',
    )
  }

  const packageName = pluginPackageName(name)

  if (context.dryRun) {
    info(`Dry run — planned plugin "${name}" from ${packageName}`)
    info(`  registration: one import + one entry in console/${CONSOLE_CONFIG}`)
    return
  }

  const range = await ensurePluginDependency(context, consoleRoot, packageName)
  const registered = await registerPlugin(consoleRoot, name, packageName)

  if (!KNOWN_PLUGINS[name]) {
    warn(
      `No built-in plugin named "${name}"; resolved ${packageName} instead. ` +
        'If that package is not published yet, run `hamolus link <path>` against a ' +
        'local Hamolus checkout.',
    )
  }

  const relativePath = relative(context.projectRoot, consoleRoot)
  await commit(
    context,
    { kind: 'plugin', id: name, label: `${pluginLabel(name)} plugin`, path: relativePath },
    {
      relativePath,
      files: registered ? 1 : 0,
      origin: `${packageName}${range ? ` ${range}` : ''} (registry)`.trim(),
      sourcePackage: packageName,
      hints: [
        'pnpm install',
        `pnpm -F ./console dev    # the plugin appears under Plugins in the sidebar`,
        `the plugin is listed in console/${CONSOLE_CONFIG} — that file is the whole registration`,
      ],
    },
  )

  if (!registered) {
    info(`plugin was already listed in console/${CONSOLE_CONFIG}`)
  }
  if (range) {
    info(`added ${packageName}@${range} to console dependencies`)
  }
}
