/**
 * Copyright 2026 Gilang Albathin Nurhabibi <https://github.com/athron98>
 *
 * Licensed under the MIT License. See the LICENSE file at the repository root.
 *
 * `hamolus add plugin <name>` — add a console plugin to an existing console.
 *
 * Plugins are opt-in by design. A console generated by `hamolus add console` has
 * no plugin registry, no plugin routes and no plugin navigation: the CLI is what
 * puts a plugin in, so the base console stays small and the dependency is visible
 * in the project's own manifest.
 *
 * The plugin is a published package plus a small registration edit, because the
 * console has to be told the plugin exists.
 */

import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'
import type { ParsedArgs } from '../args.js'
import { linkManifestFile } from '../link.js'
import {
  resolveDependencyRange,
  resolveSource,
  resolveWorkspaceDependencyVersion,
} from '../sources.js'
import { formatLabel } from '../templates.js'
import {
  addFromSource,
  commit,
  destinationFor,
  guardExisting,
  info,
  openContext,
  requirePartName,
  warn,
  writeGenerated,
  type AddContext,
} from './shared.js'

/** The contracts package every console plugin compiles against. */
const CONTRACTS_PACKAGE = '@hamolus/plugin-console-contracts'

/** Known plugin packages, so `hamolus add plugin todo` can find a sensible source. */
const KNOWN_PLUGINS: Record<string, { package: string; label: string; description: string }> = {
  todo: {
    package: '@hamolus/plugin-console-todo',
    label: 'Todo list',
    description: 'Per-land todo list stored in KV, with priorities and filters.',
  },
  kanban: {
    package: '@hamolus/plugin-console-kanban',
    label: 'Kanban board',
    description: 'Drag-and-drop kanban board stored as a single KV document.',
  },
}

const PLUGIN_DESCRIPTIONS: Record<string, string> = Object.fromEntries(
  Object.entries(KNOWN_PLUGINS).map(([id, meta]) => [id, meta.description]),
)

function pluginSourcePackage(name: string): string {
  return KNOWN_PLUGINS[name]?.package ?? `@hamolus/plugin-console-${name.replace(/_/g, '-')}`
}

function pluginLabel(name: string): string {
  return KNOWN_PLUGINS[name]?.label ?? formatLabel(name)
}

const REGISTRY_MARKER_START = '/* hamolus:plugins:start */'
const REGISTRY_MARKER_END = '/* hamolus:plugins:end */'
const IMPORTS_MARKER_START = '/* hamolus:plugins:imports:start */'
const IMPORTS_MARKER_END = '/* hamolus:plugins:imports:end */'

interface RegistryEntry {
  id: string
  component: string
  /** Import specifier written into the registry import marker. */
  specifier: string
  label: string
}

function pluginComponent(name: string): string {
  const pascal = name
    .split(/[_\-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
  return `${pascal}Plugin`
}

/**
 * Render the text that belongs between a marker pair.
 *
 * The registry block only ever carries the array *entries*: the `PLUGINS`
 * declaration, its `ConsolePlugin` type import and the `pluginById` helper belong
 * to the console itself, so re-emitting them here would duplicate the declaration.
 * Imports go into their own marker pair, because an `import` statement is not valid
 * inside an array literal.
 */
function renderRegistry(entries: RegistryEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.id.localeCompare(b.id))
  return sorted
    .map(
      (entry) =>
        `  { id: '${entry.id}', name: '${entry.label.replace(/'/g, "\\'")}', ` +
        `description: '${pluginDescription(entry.id).replace(/'/g, "\\'")}', ` +
        `component: ${entry.component} },`,
    )
    .join('\n')
}

/**
 * Description text for a registry entry.
 *
 * `description` is required by `ConsolePlugin`, so an entry without one fails the
 * console's typecheck. Descriptions come from the plugin's own package metadata
 * when it is readable, and fall back to a generic line otherwise.
 */
function pluginDescription(id: string): string {
  return PLUGIN_DESCRIPTIONS[id] ?? `${formatLabel(id)} plugin for the Hamolus console.`
}

/** Render the plugin `import` statements for the imports marker pair. */
function renderImports(entries: RegistryEntry[]): string {
  return [...entries]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((entry) => `import { ${entry.component} } from '${entry.specifier}'`)
    .join('\n')
}

/** Return the text between a marker pair, or `undefined` if the pair is absent. */
function blockBetween(
  current: string,
  startMarker: string,
  endMarker: string,
): string | undefined {
  const start = current.indexOf(startMarker)
  const end = current.indexOf(endMarker)
  if (start === -1 || end === -1 || end <= start) return undefined
  return current.slice(start + startMarker.length, end)
}

/** Replace the text between a marker pair, returning `undefined` if absent. */
function replaceBetween(
  current: string,
  startMarker: string,
  endMarker: string,
  replacement: string,
  closingIndent = '',
): string | undefined {
  const start = current.indexOf(startMarker)
  const end = current.indexOf(endMarker)
  if (start === -1 || end === -1 || end <= start) return undefined
  const head = current.slice(0, start + startMarker.length)
  const tail = current.slice(end)
  const body = replacement ? `\n${replacement}\n${closingIndent}` : `\n${closingIndent}`
  return `${head}${body}${tail}`
}

/**
 * Add a plugin to the console's registry.
 *
 * The registry is a CLI-managed block delimited by markers. Rather than patching
 * individual lines — which silently corrupts a file the moment its formatting
 * changes — the block is parsed into entries and re-rendered in full. That makes
 * the operation idempotent, order-stable, and safe to re-run.
 *
 * Returns `true` when the file changed.
 */
async function registerPlugin(consoleRoot: string, name: string, specifier: string): Promise<boolean> {
  const registryPath = join(consoleRoot, 'src', 'plugins', 'registry.ts')

  let entries: RegistryEntry[] = []
  const imports = new Map<string, string>()
  if (existsSync(registryPath)) {
    const current = await readFile(registryPath, 'utf8')
    // Parse each marker block on its own. A single cross-file regex (an import
    // matched to some later `{ id: … }`) mis-associates entries as soon as the
    // file is reformatted, which is exactly the fragility this replaces.
    const importBlock = blockBetween(current, IMPORTS_MARKER_START, IMPORTS_MARKER_END) ?? ''
    for (const match of importBlock.matchAll(/import\s*\{\s*(\w+)\s*\}\s*from\s*'([^']+)'/g)) {
      const component = match[1] as string
      imports.set(component, match[2] as string)
    }

    const entryBlock = blockBetween(current, REGISTRY_MARKER_START, REGISTRY_MARKER_END) ?? ''
    for (const match of entryBlock.matchAll(
      /\{\s*id:\s*'([^']+)',\s*name:\s*'((?:[^'\\]|\\.)*)',\s*description:\s*'(?:[^'\\]|\\.)*',\s*component:\s*(\w+)\s*,?\s*\}/g,
    )) {
      const component = match[3] as string
      const id = match[1] as string
      // Prefer the id-derived label so a known plugin keeps its curated wording.
      const label = KNOWN_PLUGINS[id]?.label ?? (match[2] as string).replace(/\\'/g, "'")
      entries.push({
        id,
        component,
        label,
        specifier: imports.get(component) ?? pluginSourcePackage(id),
      })
    }
  }

  if (entries.some((entry) => entry.id === name)) return false

  entries.push({
    id: name,
    component: pluginComponent(name),
    specifier,
    label: pluginLabel(name),
  })

  const renderedEntries = renderRegistry(entries)
  const renderedImports = renderImports(entries)

  if (existsSync(registryPath)) {
    const current = await readFile(registryPath, 'utf8')

    const withEntries = replaceBetween(
      current,
      REGISTRY_MARKER_START,
      REGISTRY_MARKER_END,
      renderedEntries,
      '  ',
    )
    const next = withEntries
      ? replaceBetween(withEntries, IMPORTS_MARKER_START, IMPORTS_MARKER_END, renderedImports)
      : undefined

    if (next && next !== current) {
      await writeFile(registryPath, next, 'utf8')
      return true
    }

    // No markers at all: fall back to appending a complete, self-contained block.
    if (!withEntries) {
      await writeFile(
        registryPath,
        `${current.trimEnd()}\n\n${renderedImports}\n\nexport const PLUGINS: ConsolePlugin[] = [\n${renderedEntries}\n]\n`,
        'utf8',
      )
      return true
    }
    return false
  }

  await writeFile(
    registryPath,
    `import type { ConsolePlugin } from './types'\n\n${renderedImports}\n\nexport const PLUGINS: ConsolePlugin[] = [\n${renderedEntries}\n]\n`,
    'utf8',
  )
  return true
}

/**
 * Declare the plugin contracts package in the console manifest.
 *
 * A plugin imports the shared `ConsolePlugin` / `PluginPageProps` shapes and the
 * StyleX token subpath from `@hamolus/plugin-console-contracts`. When the source
 * is copied into the console (`--source`) or pulled from the registry, that
 * package is a real dependency of the *console*, not an implementation detail of
 * the plugin, so the console manifest has to name it. Without this the copied
 * source fails to resolve both specifiers.
 *
 * A `workspace:` range coming from the plugin's own manifest is rewritten onto a
 * published range, because the generated project lives outside this monorepo.
 */
async function ensureContractsDependency(
  context: AddContext,
  consoleRoot: string,
  sourceDirectory: string,
): Promise<string | undefined> {
  const manifestPath = join(consoleRoot, 'package.json')
  let manifest: {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }
  try {
    manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  } catch {
    return undefined
  }

  const existing =
    manifest.dependencies?.[CONTRACTS_PACKAGE] ??
    manifest.devDependencies?.[CONTRACTS_PACKAGE]
  // The dependency is present, but the project's link still has to be re-applied: the
  // console was linked when it was added, before this dependency existed.
  if (existing) {
    await linkManifestFile(manifestPath, context.link)
    return undefined
  }

  let requested = '*'
  try {
    const source = JSON.parse(
      await readFile(join(sourceDirectory, 'package.json'), 'utf8'),
    ) as { dependencies?: Record<string, string> }
    requested = source.dependencies?.[CONTRACTS_PACKAGE] ?? '*'
  } catch {
    // A source without a readable manifest still gets a usable range below.
  }

  const discovered = await resolveWorkspaceDependencyVersion(
    sourceDirectory,
    CONTRACTS_PACKAGE,
  )
  const range = resolveDependencyRange(requested, requested, discovered)

  manifest.dependencies ??= {}
  manifest.dependencies[CONTRACTS_PACKAGE] = range
  // Keep the object stable for reproducible diffs instead of appending blindly.
  manifest.dependencies = Object.fromEntries(
    Object.entries(manifest.dependencies).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  )
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)
  // A freshly written range must not survive as a registry spec in a linked project,
  // or `pnpm install` reaches for an unpublished package.
  for (const spec of await linkManifestFile(manifestPath, context.link)) info(`link  ${spec}`)
  return range
}

export async function runAddPlugin(args: ParsedArgs): Promise<void> {
  const context = await openContext(args)
  const name = requirePartName(args, 'plugin')
  const destination = destinationFor(context, join('console', 'src', 'plugins', name))
  const relativePath = relative(context.projectRoot, destination)

  guardExisting(context, 'plugin', name, destination)

  const consoleRoot = join(context.projectRoot, 'console')
  if (!existsSync(join(consoleRoot, 'package.json'))) {
    throw new Error(
      'This project has no console yet. Add one first:\n  hamolus add console',
    )
  }

  const packageName = pluginSourcePackage(name)

  if (context.dryRun) {
    info(`Dry run — planned plugin "${name}" from ${packageName}`)
    return
  }

  const source = await resolveSource({
    defaultPackage: packageName,
    projectRoot: context.projectRoot,
    explicitSource: args.options.source,
    explicitPackage: args.options.package,
  linkRoot: context.link?.root,
  })

  const files = await addFromSource({ context, sourceDirectory: source.directory, destination })
  // The plugin source is copied into `console/src/plugins/<name>/`, so the
  // registry imports the copy through a relative specifier. A bare package
  // specifier would only resolve if the plugin were also an installed dependency,
  // which the generated console deliberately does not gain: the copy *is* the
  // dependency, and it keeps the plugin editable inside the project.
  const specifier = `./${name}/src/index`
  const registered = await registerPlugin(consoleRoot, name, specifier)
  const contractsRange = await ensureContractsDependency(context, consoleRoot, source.directory)

  await writeGenerated(context, join(destination, '.gitkeep'), '')

  if (!KNOWN_PLUGINS[name]) {
    warn(
      `No built-in plugin named "${name}"; resolved ${packageName} instead. ` +
        'If that package is not published yet, pass --source <path>.',
    )
  }

  await commit(
    context,
    { kind: 'plugin', id: name, label: `${pluginLabel(name)} plugin`, path: relativePath },
    {
      relativePath,
      files,
      origin: `${source.package} ${source.version ?? ''} (${source.origin})`.trim(),
      sourcePackage: source.package,
      sourceVersion: source.version,
      hints: [
        'pnpm install',
        `pnpm -F ./console dev    # the plugin appears under Plugins in the sidebar`,
      ],
    },
  )

  if (!registered) {
    info('plugin was already registered in console/src/plugins/registry.ts')
  }

  if (contractsRange) {
    info(`added ${CONTRACTS_PACKAGE}@${contractsRange} to console dependencies`)
  }
}
